{% set name = "phreeqcrm" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/phreeqcrm-{{ version }}.tar.gz
  sha256: 6374b32ea02bd3fd101f949ac790dafe5140039516afd606f00d6c523d8cddcf

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.20,<4
    - make
    - ninja
    - swig
  host:
    - python
    - scikit-build-core
    - numpy
    - pip
  run:
    - numpy
    - python
    - pyyaml
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]
    - vcomp14        # [win]

test:
  imports:
    - phreeqcrm
  commands:
    - pytest swig/python
  requires:
    - pytest
  source_files:
    - swig/python/advect.pqi
    - swig/python/AdvectBMI_py.yaml
    - swig/python/conftest.py
    - swig/python/constants.py
    - swig/python/phreeqc.dat
    - swig/python/test_basic.py
    - swig/python/test_get_value.py
    - swig/python/test_get_value.py
    - swig/python/test_init.py
    - swig/python/test_irf.py

about:
  home: https://github.com/usgs-coupled/phreeqcrm
  summary: A reaction module for transport simulators based on the geochemical model PHREEQC.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlparkhurst
    - scharlton2
